class PlayGroundExecutor {

    public static void main(String[] args) {

        PlayGround info1 = new PlayGround();
        info1.setPlayerId(1);
        info1.setName("Asha");
        info1.setGameType("Indoor");
        info1.setGameName("Chess");
        info1.setLocation("Room");
		System.out.println("PlayGround 1 ");
        System.out.println(info1.getPlayerId());
        System.out.println(info1.getName());
        System.out.println(info1.getGameType());
        System.out.println(info1.getGameName());
        System.out.println(info1.getLocation());

        PlayGround info2 = new PlayGround();
        info2.setPlayerId(2);
        info2.setName("Neha");
        info2.setGameType("Outdoor");
        info2.setGameName("Cricket");
        info2.setLocation("Ground");
		System.out.println("PlayGround 2 ");
        System.out.println(info2.getPlayerId());
        System.out.println(info2.getName());
        System.out.println(info2.getGameType());
        System.out.println(info2.getGameName());
        System.out.println(info2.getLocation());

        PlayGround info3 = new PlayGround();
        info3.setPlayerId(3);
        info3.setName("Pooja");
        info3.setGameType("Indoor");
        info3.setGameName("Carrom");
        info3.setLocation("Hall");
		System.out.println("PlayGround 3 ");
        System.out.println(info3.getPlayerId());
        System.out.println(info3.getName());
        System.out.println(info3.getGameType());
        System.out.println(info3.getGameName());
        System.out.println(info3.getLocation());

        PlayGround info4 = new PlayGround();
        info4.setPlayerId(4);
        info4.setName("Riya");
        info4.setGameType("Outdoor");
        info4.setGameName("Badminton");
        info4.setLocation("Court");
		System.out.println("PlayGround 4 ");
        System.out.println(info4.getPlayerId());
        System.out.println(info4.getName());
        System.out.println(info4.getGameType());
        System.out.println(info4.getGameName());
        System.out.println(info4.getLocation());

        PlayGround info5 = new PlayGround();
        info5.setPlayerId(5);
        info5.setName("Sneha");
        info5.setGameType("Indoor");
        info5.setGameName("Ludo");
        info5.setLocation("Home");
		System.out.println("PlayGround 5");
        System.out.println(info5.getPlayerId());
        System.out.println(info5.getName());
        System.out.println(info5.getGameType());
        System.out.println(info5.getGameName());
        System.out.println(info5.getLocation());

        PlayGround info6 = new PlayGround();
        info6.setPlayerId(6);
        info6.setName("Divya");
        info6.setGameType("Outdoor");
        info6.setGameName("Kho Kho");
        info6.setLocation("Ground");
		System.out.println("PlayGround 6 ");
        System.out.println(info6.getPlayerId());
        System.out.println(info6.getName());
        System.out.println(info6.getGameType());
        System.out.println(info6.getGameName());
        System.out.println(info6.getLocation());

        PlayGround info7 = new PlayGround();
        info7.setPlayerId(7);
        info7.setName("Anjali");
        info7.setGameType("Indoor");
        info7.setGameName("Table Tennis");
        info7.setLocation("Club");
		System.out.println("PlayGround 7 ");
        System.out.println(info7.getPlayerId());
        System.out.println(info7.getName());
        System.out.println(info7.getGameType());
        System.out.println(info7.getGameName());
        System.out.println(info7.getLocation());

        PlayGround info8 = new PlayGround();
        info8.setPlayerId(8);
        info8.setName("Kavya");
        info8.setGameType("Outdoor");
        info8.setGameName("Football");
        info8.setLocation("Field");
		System.out.println("PlayGround 8 ");
        System.out.println(info8.getPlayerId());
        System.out.println(info8.getName());
        System.out.println(info8.getGameType());
        System.out.println(info8.getGameName());
        System.out.println(info8.getLocation());

        PlayGround info9 = new PlayGround();
        info9.setPlayerId(9);
        info9.setName("Megha");
        info9.setGameType("Indoor");
        info9.setGameName("Cards");
        info9.setLocation("Room");
		System.out.println("PlayGround 9 ");
        System.out.println(info9.getPlayerId());
        System.out.println(info9.getName());
        System.out.println(info9.getGameType());
        System.out.println(info9.getGameName());
        System.out.println(info9.getLocation());

        PlayGround info10 = new PlayGround();
        info10.setPlayerId(10);
        info10.setName("Isha");
        info10.setGameType("Outdoor");
        info10.setGameName("Volleyball");
        info10.setLocation("Court");
		System.out.println("PlayGround 10 ");
        System.out.println(info10.getPlayerId());
        System.out.println(info10.getName());
        System.out.println(info10.getGameType());
        System.out.println(info10.getGameName());
        System.out.println(info10.getLocation());
		
		PlayGround info11 = new PlayGround();
info11.setPlayerId(11);
info11.setName("Pallavi");
info11.setGameType("Indoor");
info11.setGameName("Snake and Ladder");
info11.setLocation("Home");
System.out.println("PlayGround 11 ");
System.out.println(info11.getPlayerId());
System.out.println(info11.getName());
System.out.println(info11.getGameType());
System.out.println(info11.getGameName());
System.out.println(info11.getLocation());

PlayGround info12 = new PlayGround();
info12.setPlayerId(12);
info12.setName("Anu");
info12.setGameType("Outdoor");
info12.setGameName("Tennis");
info12.setLocation("Court");
System.out.println("PlayGround 12 ");
System.out.println(info12.getPlayerId());
System.out.println(info12.getName());
System.out.println(info12.getGameType());
System.out.println(info12.getGameName());
System.out.println(info12.getLocation());

PlayGround info13 = new PlayGround();
info13.setPlayerId(13);
info13.setName("Bhavya");
info13.setGameType("Indoor");
info13.setGameName("Puzzle");
info13.setLocation("Room");
System.out.println("PlayGround 13 ");
System.out.println(info13.getPlayerId());
System.out.println(info13.getName());
System.out.println(info13.getGameType());
System.out.println(info13.getGameName());
System.out.println(info13.getLocation());

PlayGround info14 = new PlayGround();
info14.setPlayerId(14);
info14.setName("Chitra");
info14.setGameType("Outdoor");
info14.setGameName("Basketball");
info14.setLocation("Ground");
System.out.println("PlayGround 14 ");
System.out.println(info14.getPlayerId());
System.out.println(info14.getName());
System.out.println(info14.getGameType());
System.out.println(info14.getGameName());
System.out.println(info14.getLocation());

PlayGround info15 = new PlayGround();
info15.setPlayerId(15);
info15.setName("Deepika");
info15.setGameType("Indoor");
info15.setGameName("Uno");
info15.setLocation("Hall");
System.out.println("PlayGround 15 ");
System.out.println(info15.getPlayerId());
System.out.println(info15.getName());
System.out.println(info15.getGameType());
System.out.println(info15.getGameName());
System.out.println(info15.getLocation());

PlayGround info16 = new PlayGround();
info16.setPlayerId(16);
info16.setName("Esha");
info16.setGameType("Outdoor");
info16.setGameName("Kabaddi");
info16.setLocation("Ground");
System.out.println("PlayGround 16 ");
System.out.println(info16.getPlayerId());
System.out.println(info16.getName());
System.out.println(info16.getGameType());
System.out.println(info16.getGameName());
System.out.println(info16.getLocation());

PlayGround info17 = new PlayGround();
info17.setPlayerId(17);
info17.setName("Farah");
info17.setGameType("Indoor");
info17.setGameName("Chess");
info17.setLocation("Club");
System.out.println("PlayGround 17 ");
System.out.println(info17.getPlayerId());
System.out.println(info17.getName());
System.out.println(info17.getGameType());
System.out.println(info17.getGameName());
System.out.println(info17.getLocation());

PlayGround info18 = new PlayGround();
info18.setPlayerId(18);
info18.setName("Gauri");
info18.setGameType("Outdoor");
info18.setGameName("Running");
info18.setLocation("Track");
System.out.println("PlayGround 18 ");
System.out.println(info18.getPlayerId());
System.out.println(info18.getName());
System.out.println(info18.getGameType());
System.out.println(info18.getGameName());
System.out.println(info18.getLocation());

PlayGround info19 = new PlayGround();
info19.setPlayerId(19);
info19.setName("Hema");
info19.setGameType("Indoor");
info19.setGameName("Carrom");
info19.setLocation("Room");
System.out.println("PlayGround 19 ");
System.out.println(info19.getPlayerId());
System.out.println(info19.getName());
System.out.println(info19.getGameType());
System.out.println(info19.getGameName());
System.out.println(info19.getLocation());
  
PlayGround info20 = new PlayGround();
info20.setPlayerId(20);
info20.setName("Ishita");
info20.setGameType("Outdoor");
info20.setGameName("Cycling");
info20.setLocation("Road");
System.out.println("PlayGround 20 ");
System.out.println(info20.getPlayerId());
System.out.println(info20.getName());
System.out.println(info20.getGameType());
System.out.println(info20.getGameName());
System.out.println(info20.getLocation());

PlayGround info21 = new PlayGround();
info21.setPlayerId(21);
info21.setName("Jaya");
info21.setGameType("Indoor");
info21.setGameName("Ludo");
info21.setLocation("Home");
System.out.println("PlayGround 21 ");
System.out.println(info21.getPlayerId());
System.out.println(info21.getName());
System.out.println(info21.getGameType());
System.out.println(info21.getGameName());
System.out.println(info21.getLocation());

PlayGround info22 = new PlayGround();
info22.setPlayerId(22);
info22.setName("Kiran");
info22.setGameType("Outdoor");
info22.setGameName("Throwball");
info22.setLocation("Ground");
System.out.println("PlayGround 22 ");
System.out.println(info22.getPlayerId());
System.out.println(info22.getName());
System.out.println(info22.getGameType());
System.out.println(info22.getGameName());
System.out.println(info22.getLocation());

PlayGround info23 = new PlayGround();
info23.setPlayerId(23);
info23.setName("Lavanya");
info23.setGameType("Indoor");
info23.setGameName("Cards");
info23.setLocation("Room");
System.out.println("PlayGround 23 ");
System.out.println(info23.getPlayerId());
System.out.println(info23.getName());
System.out.println(info23.getGameType());
System.out.println(info23.getGameName());
System.out.println(info23.getLocation());

PlayGround info24 = new PlayGround();
info24.setPlayerId(24);
info24.setName("Manasa");
info24.setGameType("Outdoor");
info24.setGameName("Hockey");
info24.setLocation("Field");
System.out.println("PlayGround 24 ");
System.out.println(info24.getPlayerId());
System.out.println(info24.getName());
System.out.println(info24.getGameType());
System.out.println(info24.getGameName());
System.out.println(info24.getLocation());

PlayGround info25 = new PlayGround();
info25.setPlayerId(25);
info25.setName("Nikita");
info25.setGameType("Indoor");
info25.setGameName("Puzzle");
info25.setLocation("Hall");
System.out.println("PlayGround 25 ");
System.out.println(info25.getPlayerId());
System.out.println(info25.getName());
System.out.println(info25.getGameType());
System.out.println(info25.getGameName());
System.out.println(info25.getLocation());

PlayGround info26 = new PlayGround();
info26.setPlayerId(26);
info26.setName("Oviya");
info26.setGameType("Outdoor");
info26.setGameName("Skating");
info26.setLocation("Park");
System.out.println("PlayGround 26 ");
System.out.println(info26.getPlayerId());
System.out.println(info26.getName());
System.out.println(info26.getGameType());
System.out.println(info26.getGameName());
System.out.println(info26.getLocation());

PlayGround info27 = new PlayGround();
info27.setPlayerId(27);
info27.setName("Pavitra");
info27.setGameType("Indoor");
info27.setGameName("Chess");
info27.setLocation("Club");
System.out.println("PlayGround 27 ");
System.out.println(info27.getPlayerId());
System.out.println(info27.getName());
System.out.println(info27.getGameType());
System.out.println(info27.getGameName());
System.out.println(info27.getLocation());

PlayGround info28 = new PlayGround();
info28.setPlayerId(28);
info28.setName("Qamar");
info28.setGameType("Outdoor");
info28.setGameName("Badminton");
info28.setLocation("Court");
System.out.println("PlayGround 28 ");
System.out.println(info28.getPlayerId());
System.out.println(info28.getName());
System.out.println(info28.getGameType());
System.out.println(info28.getGameName());
System.out.println(info28.getLocation());

PlayGround info29 = new PlayGround();
info29.setPlayerId(29);
info29.setName("Rashmi");
info29.setGameType("Indoor");
info29.setGameName("Carrom");
info29.setLocation("Room");
System.out.println("PlayGround 29 ");
System.out.println(info29.getPlayerId());
System.out.println(info29.getName());
System.out.println(info29.getGameType());
System.out.println(info29.getGameName());
System.out.println(info29.getLocation());  

   }
	
}